name: Release
on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      publishMS:
        description: 'Publish to MS marketplace'
        type: boolean
        required: true
        default: "true"
      publishOVSX:
        description: 'Publish to OpenVSX'
        type: boolean
        required: true
        default: "true"
      publishGH:
        description: 'Publish to GitHub releases'
        type: boolean
        required: true
        default: "true"

jobs:
  package:
    runs-on: ubuntu-latest
    outputs:
      packagePath: ${{ steps.setup.outputs.packagePath }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm i

      - name: Setup package path
        id: setup
        run: echo "::set-output name=packagePath::$(node -e "console.log('./' + require('./package.json').name + '-v' + require('./package.json').version + '.vsix')")"

      - name: Package
        env:
          VSIX_PACKAGE_PATH: ${{ steps.setup.outputs.packagePath }}
        run: npx gulp package

  publishMS:
    runs-on: ubuntu-latest
    needs: package
    if: github.event.inputs.publishMS == 'true'
    steps:
      - name: Publish to MS marketplace
        run: npx vsce publish -p ${{ secrets.VSCE_PAT }} --packagePath ${{ needs.package.outputs.packagePath }}

  publishOVSX:
    runs-on: ubuntu-latest
    needs: package
    if: github.event.inputs.publishOVSX == 'true'
    steps:
      - name: Publish to OpenVSX
        run: npx ovsx publish -p ${{ secrets.OVSX_PAT }} --packagePath ${{ needs.package.outputs.packagePath }}
  
  publishGH:
    runs-on: ubuntu-latest
    needs: package
    if: github.event.inputs.publishGH == 'true'
    steps:
      - name: Get tag
        id: get-tag
        run: |
          $version = (Get-Content ./package.json -Raw | ConvertFrom-Json).version
          Write-Host "tag: release/$version"
          Write-Host "::set-output name=tag::release/$version"
          Write-Host "::set-output name=version::$version"
        shell: pwsh

      - name: Commit tagger
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.get-tag.outputs.tag }}
          
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-tag.outputs.tag }}
          release_name: Release ${{ steps.get-tag.outputs.version }}
          draft: false
          prerelease: false
          
      - name: Upload assets to a Release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: ${{ needs.package.outputs.packagePath }}
          release-tag:  ${{ steps.get-tag.outputs.tag }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}